---
# updated version of GitHubActions_Demo3_NodeJS
name: build nodeJS application
on: 
 push:
  branches:
   - master
jobs: 
  buildJob:
    runs-on: ubuntu-latest 
    steps: 
      - name: Clone the Repo 
        uses: actions/checkout@v5 
      - name: Install nodejs
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci 
      - name: Run tests 
        run: npm test
      - name: Build code 
        run: npm run build

      - name: upload Test & Build reports to github repo 
        uses: actions/upload-artifact@v4
        with: 
         name: upload files
         path: |
          /home/runner/work/GitHubActions_Demo4.2_NodeJS_Upload_Artifact/GitHubActions_Demo4.2_NodeJS_Upload_Artifact/test.json
          dist/assets/logo.76a8d26b.png 
          dist/index.html
          dist/assets/index.34ed278d.css
          dist/assets/index.d590f20c.js
